name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./GitHubActionTest --file Dockerfile --tag jvannor/github-action-test:$(date +%s)
    - name: Push
      run: docker push jvannor/github-action-test:$(date +%s)
